print("I Love Python")
myName = input()
print(myName)
print("My Name is " + myName)
print(4 + 3.0)
print(6 / 3)
print(4**3)
print(6*3.0)
print(15 % 4)
print(9.0 - 4)
print(4 + 3**5.0)
num1 = input()
print(num1)
num2 = input()
print(num2)
print(num1 + num2)
print(int(num1) + int(num2))
